apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubewatch

resources:
  - ../../base
  - ../../../../backend/config/overlays/loc
  - backend-migration-job.yaml
  - ingress.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml

nameSuffix: -local
