apiVersion: v1
kind: Pod
metadata:
  name: pvc-reader
  namespace: kubewatch
spec:
  restartPolicy: Never
  containers:
    - name: reader
      image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args:
        - sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: kubewatch-data-lab
