apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader-lab
  namespace: kubewatch
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["kubewatch-backend-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-lab
  namespace: kubewatch
subjects:
  - kind: ServiceAccount
    name: secret-reader-lab
    namespace: kubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader-lab
