apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: kubewatch-backend-config
    envs:
      - common.env

generatorOptions:
  labels:
    app.kubernetes.io/name: kubewatch-backend
    app.kubernetes.io/part-of: kubewatch
