apiVersion: v1
kind: Service
metadata:
  name: kubewatch-backend
  labels:
    app.kubernetes.io/name: kubewatch-backend
    app.kubernetes.io/part-of: kubewatch
spec:
  selector:
    app.kubernetes.io/name: kubewatch-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
