apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubewatch-backend
  labels:
    app.kubernetes.io/name: kubewatch-backend
    app.kubernetes.io/part-of: kubewatch
  annotations:
    iam.gke.io/gcp-service-account: kubewatch-backend-dev@study-gcp-cicd.iam.gserviceaccount.com
