apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubewatch-dev

resources:
  - namespace.yaml
  - ../../../../backend/config/overlays/dev
  - backend-serviceaccount.yaml
  - collector-serviceaccount.yaml
  - collector-rbac.yaml
  - resource-collector-cronjob.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-migration-job.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

images:
  - name: kubewatch-backend
    newName: asia-northeast3-docker.pkg.dev/study-gcp-cicd/study-cicd-images/kubewatch-backend
    digest: sha256:8118ba5a3d83ec7c71176ffdd4633a6b67e2e38ac5bfb21456b8690cc408278e
  - name: kubewatch-frontend
    newName: asia-northeast3-docker.pkg.dev/study-gcp-cicd/study-cicd-images/kubewatch-frontend
    digest: sha256:1d62977b08534c72e0fe8549180391910acfe553e968a94a1f1451c709c05580
