apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kubewatch-external
  labels:
    app.kubernetes.io/part-of: kubewatch
    app.kubernetes.io/environment: dev
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
