apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubewatch-dev

resources:
  - gateway.yaml
  - httproute.yaml
  - backend-healthcheckpolicy.yaml
  - frontend-healthcheckpolicy.yaml
